# init_db.py

import asyncpg
import asyncio
from config import DB_CONFIG

CREATE_SCHEMAS = """
    CREATE SCHEMA IF NOT EXISTS auth;
    CREATE SCHEMA IF NOT EXISTS dialog;
"""

CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS auth.users (
       id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    uuid uuid DEFAULT gen_random_uuid(),
    source_system_id integer,
    source_user_id integer,
    username character varying(100) COLLATE pg_catalog."default",
    first_name character varying(200) COLLATE pg_catalog."default",
    last_name character varying(200) COLLATE pg_catalog."default",
    password_hash character varying(500) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    mobile character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    last_login_at timestamp without time zone ,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_shamsi_at integer,
    updated_shamsi_at integer
);
"""

CREATE_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS auth.roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_shamsi_at integer,
    updated_shamsi_at integer
);
"""

CREATE_USERS_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS auth.user_roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id bigint NOT NULL,
    role_id integer NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_shamsi_at integer,
    updated_shamsi_at integer,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id)
)
"""

CREATE_QUESTIONS_TABLE = """
CREATE TABLE IF NOT EXISTS dialog.questions (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    type TEXT DEFAULT 'text',
    order integer ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_shamsi_at integer,
    updated_shamsi_at integer
);
"""

CREATE_ANSWERS_TABLE = """
CREATE TABLE IF NOT EXISTS dialog.answers (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id INTEGER NOT NULL,
    answer TEXT,
    created_at TIMESTAMP DEFAULT now(),
    created_shamsi_at integer
);
"""


CREATE_USER_STATE_TABLE = """
    CREATE TABLE IF NOT EXISTS dialog.user_states (
        user_id bigint PRIMARY KEY,
        current_question_id integer,
        updated_at timestamp DEFAULT now()
    );
"""

async def init_db():
    conn = await asyncpg.connect(
        user=DB_CONFIG["db_user"],
        password=DB_CONFIG["db_password"],
        database=DB_CONFIG["db_database"],
        host=DB_CONFIG["db_host"],
        port=DB_CONFIG["db_port"],
    )
    print("✅ Connected to DataBase")

    await conn.execute(CREATE_SCHEMAS)
    await conn.execute(CREATE_USERS_TABLE)
    await conn.execute(CREATE_ROLES_TABLE)
    await conn.execute(CREATE_USERS_ROLES_TABLE)
    await conn.execute(CREATE_QUESTIONS_TABLE)
    await conn.execute(CREATE_ANSWERS_TABLE)

    print("✅ Tables are created ")
    await conn.close()

if __name__ == "__main__":
    asyncio.run(init_db())
